name: Python Tests

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  test:
    runs-on: ubuntu-latest 

    steps:
      - name: Check out code
        uses: actions/checkout@v2  

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Atualiza o pip
          pip install -r requirements.txt  # Instala as dependências do projeto (certifique-se de ter esse arquivo)

      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -q  # Roda os testes do pytest
